<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_calendar_mvc"
 *
 * Auto generated by SAV Library Kickstarter 20-09-18
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Calendar Mvc',
    'description' => 'Simple calendar with frontend input',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-9.9.99',
            'sav_library_mvc' => '1.2.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>