<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_calendar_mvc"
 *
 * Auto generated by SAV Library Kickstarter 19-05-17
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Calendar Mvc',
    'description' => 'Simple calendar with frontend input',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>