<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example1"
 *
 * Auto generated by SAV Library Kickstarter 12-09-18
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example1 - Contact list',
    'description' => 'A simple contact list (from  http://www.typo3journal.info/articles/developpement/developpement-extensions-1.html)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-9.9.99',
            'sav_library_plus' => '1.2.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>