<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example2"
 *
 * Auto generated by SAV Library Kickstarter 12-12-17
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example2 - CD Album',
    'description' => 'CD Album list (from Kasper\'s video Episode III)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.9.99',
            'sav_library_plus' => '1.0.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>