<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example0"
 *
 * Auto generated by SAV Library Kickstarter 2026-07-22
 *
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example0 - Test',
    'description' => 'An extension to illustrate the SAV Library Plus',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '14.3.0',
    'constraints' => [
        'depends' => [
            'typo3' => '13.4.0-14.3.99',
            'sav_library_plus' => '14.3.0-14.3.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];