<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example0"
 *
 * Auto generated by SAV Library Kickstarter 05-07-16
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = array(
    'title' => 'SAV Library Example0 - Test',
    'description' => 'An extension to illustrate the SAV Library Plus',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.1.99',
            'sav_library_plus' => '',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>