routeEnhancers:
  SavCalendarMvc:
    type: Extbase
    extension: SavCalendarMvc
    plugin: Default
    routes:
      - routePath: '/savcalendarmvc/default'
        _controller: 'Default::list'
      - routePath: '/savcalendarmvc/default/{special}'
        _controller: 'Default::list'
      - routePath: '/savcalendarmvc/default/single/{special}'
        _controller: 'Default::single'
      - routePath: '/savcalendarmvc/default/edit/{special}'
        _controller: 'Default::edit'
      - routePath: '/savcalendarmvc/default/delete/{special}'
        _controller: 'Default::delete'
      - routePath: '/savcalendarmvc/default/subform/delete/{special}'
        _controller: 'Default::deleteInSubform'
      - routePath: '/savcalendarmvc/default/subform/up/{special}'
        _controller: 'Default::upInSubform'
      - routePath: '/savcalendarmvc/default/subform/down/{special}'
        _controller: 'Default::downInSubform'
      - routePath: '/savcalendarmvc/default/file/delete/{special}'
        _controller: 'Default::deleteFile'
      - routePath: '/savcalendarmvc/default/export/{special}'
        _controller: 'Default::export'
      - routePath: '/savcalendarmvc/admin'
        _controller: 'Admin::list'
      - routePath: '/savcalendarmvc/admin/{special}'
        _controller: 'Admin::list'
      - routePath: '/savcalendarmvc/admin/single/{special}'
        _controller: 'Admin::single'
      - routePath: '/savcalendarmvc/admin/edit/{special}'
        _controller: 'Admin::edit'
      - routePath: '/savcalendarmvc/admin/delete/{special}'
        _controller: 'Admin::delete'
      - routePath: '/savcalendarmvc/admin/subform/delete/{special}'
        _controller: 'Admin::deleteInSubform'
      - routePath: '/savcalendarmvc/admin/subform/up/{special}'
        _controller: 'Admin::upInSubform'
      - routePath: '/savcalendarmvc/admin/subform/down/{special}'
        _controller: 'Admin::downInSubform'
      - routePath: '/savcalendarmvc/admin/file/delete/{special}'
        _controller: 'Admin::deleteFile'
      - routePath: '/savcalendarmvc/admin/export/{special}'
        _controller: 'Admin::export'
    requirements:
      special: '[a-z0-9\-]+'     