categories:
  SavBasicExample0:
    label: 'SavBasicExample0'
  SavBasicExample0.templates:
    label: 'Templates'
    parent: SavBasicExample0
  SavBasicExample0.pages:
    label: 'Pages'
    parent: SavBasicExample0

settings:

  savBasicExample0.templateRootPath:
    label: 'Templates'
    category: SavBasicExample0.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:sav_basic_example0/Resources/Private/Templates/'

  savBasicExample0.partialRootPath:
    label: 'Partials'
    category: SavBasicExample0.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:sav_basic_example0/Resources/Private/Partials/'

  savBasicExample0.layoutRootPath:
    label: 'Layouts'
    category: SavBasicExample0.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:sav_basic_example0/Resources/Private/Layouts/'

  savBasicExample0.storagePid:
    label: 'Default storage PID'
    category: SavBasicExample0.pages
    description: 'Folder that stores all reccords'
    type: int
    default: 0