<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example6"
 *
 * Auto generated by SAV Library Kickstarter 18-01-18
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example6 - Email and RTF',
    'description' => 'Sending an email and generating a RTF file with the SAV Library',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-9.0.0',
            'sav_library_plus' => '1.2.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>