<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_basic_example0"
 *
 * Auto generated by SAV Library Kickstarter 23-05-16
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = array(
    'title' => 'SAV Basic Example0 - Test',
    'description' => 'An extension to test SAV Library Kickstarter for the Basic type generation (Fluid/Extbase)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.1.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>