<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_basic_example0"
 *
 * Auto generated by SAV Library Kickstarter 13-10-21
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Basic Example0 - Test',
    'description' => 'An extension to test SAV Library Kickstarter for the Basic type generation (Fluid/Extbase)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '11.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.28-11.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
