<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_basic_example0"
 *
 * Auto generated by SAV Library Kickstarter 05-02-18
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Basic Example0 - Test',
    'description' => 'An extension to test SAV Library Kickstarter for the Basic type generation (Fluid/Extbase)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-9.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>