routeEnhancers:
  SavLibraryExample9:
    type: SavLibraryPlusPlugin
    namespace: 'tx_savlibraryexample9_pi1'
    routePath: '/savLibraryExample9/{controller}/{action}/{sav_library_plus}'
    requirements:
      controller: 'Default'
      action: '[a-zA-Z]+'
      sav_library_plus: '[0-9a-f]+'