<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_download"
 *
 * Auto generated by SAV Library Kickstarter 01-05-16
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = array(
    'title' => 'SAV Download',
    'description' => 'Downloads files with category',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.0.1',
            'sav_library_plus' => '',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>