<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_download"
 *
 * Auto generated by SAV Library Kickstarter 20-05-17
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Download',
    'description' => 'Downloads files with category',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.9.99',
            'sav_library_plus' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>