routeEnhancers:
  SavLibraryExample8:
    type: SavLibraryPlusPlugin
    namespace: 'tx_savlibraryexample8_pi1'
    routePath: '/savLibraryExample8/{controller}/{action}/{sav_library_plus}'
    requirements:
      controller: 'Default'
      action: '[a-zA-Z]+'
      sav_library_plus: '[0-9a-f]+'