<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example10"
 *
 * Auto generated by SAV Library Kickstarter 20-05-17
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example10 - Using TypoScript',
    'description' => 'Simple gallery to show how to use TypoScript in SAV Library Extension. It includes images display and google maps',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-6.2.99',
            'sav_library_plus' => '',
            'wec_map' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>