routeEnhancers:
  SavLibraryExample3:
    type: SavLibraryPlusPlugin
    namespace: 'tx_savlibraryexample3_pi1'
    routePath: '/savLibraryExample3/{controller}/{action}/{sav_library_plus}'
    requirements:
      controller: 'Default'
      action: '[a-zA-Z]+'
      sav_library_plus: '[0-9a-f]+'