<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_library_example3"
 *
 * Auto generated by SAV Library Kickstarter 05-08-19
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Library Example3 - CD Album (Advanced)',
    'description' => 'CD Album list (from Kasper\'s video Episode III)',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'sav_library_plus' => '1.2.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>